name: Deploy to Sirkadiyen Server

# Sadece 'main' branch'ine (ana dala) push yapıldığında tetiklensin
on:
  push:
    branches:
      - main  # veya 'production' hangisini kullanıyorsanız

jobs:
  deploy:
    # Bu işin nerede çalışacağını belirtir. 
    # 'self-hosted' dediğimizde, sizin sunucunuzdaki runner'a gider.
    runs-on: self-hosted

    env:
      NODE_OPTIONS: "--dns-result-order=ipv4first"

    # Projenin sunucuda bulunduğu dizini buraya yazın
    # Bu, 'ghrunner' kullanıcısının ev dizinindeki proje yolu olmalı
    defaults:
      run:
        working-directory: /home/ghrunner/ders_programi/ders_programi

    steps:
      - name: 1. Kodu Çek (Checkout)
        # GitHub'dan en güncel kodu runner'ın çalışma dizinine indirir
        uses: actions/checkout@v4
        

      - name: 2. Node.js Sürümünü Ayarla
        uses: actions/setup-node@v4
        with:
          node-version: '22.11' # Sunucunuzdaki sürümle aynı olsun

      - name: 3. Yeni Kodu Proje Dizinine Kopyala (rsync)
        # $GITHUB_WORKSPACE'teki kodu asıl proje dizinimize kopyalıyoruz
        # --delete: Yeni committe silinmiş olan dosyaları proje dizininden de siler
        # -a: Arşiv modu (izinleri, sembolik linkleri vb. korur)
        run: rsync -a --delete --exclude '.env' --exclude '.env.local' --exclude 'node_modules' $GITHUB_WORKSPACE/ /home/ghrunner/ders_programi/ders_programi/  
      - name: 4. Bağımlılıkları Yükle (Değişiklik varsa)
        run: npm install
        working-directory: /home/ghrunner/ders_programi/ders_programi

      - name: 5. Veritabanı Değişikliklerini Uygula
        # Eğer schema.prisma'da değişiklik yaptıysanız bu şart.
        run: npx prisma db push
        working-directory: /home/ghrunner/ders_programi/ders_programi

      - name: 6. Prisma Client'ı Yeniden Oluştur
        run: npx prisma generate
        working-directory: /home/ghrunner/ders_programi/ders_programi
        
      - name: 7. Projeyi Yeniden Derle (Build)
        run: npm run build
        working-directory: /home/ghrunner/ders_programi/ders_programi
      - name: 8. Projeyi Yeniden Başlat
        run: /home/ghrunner/.nvm/versions/node/v22.11.0/bin/pm2 restart sirkadiyen
        working-directory: /home/ghrunner/ders_programi/ders_programi

      